@baseUrl = http://localhost:4000
@contentType = application/json
@authToken = {{login.response.headers.Authorization}}

### 
# @name createAdmin
POST {{baseUrl}}/admin
Content-Type: {{contentType}}

{
    "email":"admin@admin.admin",
    "password":"admin"
}

###
POST {{baseUrl}}/merchants
Content-Type: {{contentType}}

{
    "email":"tttttt@tttttt.tttttt",
    "password":"tttttt",
    "companyName":"tttttt",
    "kbis":"tttttt",
    "tel":"tttttt",
    "site":"tttttt",
    "urlConfirmation":"urlZaraConfirmation",
    "urlAnnulation":"urlZaraAnnulation",
    "quote":"euro"
}



### Authentification
POST {{baseUrl}}/logout
Authorization: {{authToken}}

###
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email":"tttttt@tttttt.tttttt",
    "password":"tttttt"
}

### Les Marchands
GET {{baseUrl}}/merchants
Authorization: {{authToken}}

###
GET {{baseUrl}}/merchants/26
Authorization: {{authToken}}

###
PUT {{baseUrl}}/merchants/26/validate
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
DELETE {{baseUrl}}/merchants/40/credentials
Content-Type: {{contentType}}
Authorization: {{authToken}}



### Les Transaction
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "priceTotal": "100",
    "quote": "Euro",
    "delivery": "adresse",
    "mid":"40",
    "commandId": "1234",
    "clientInformation": "aaa aa aaaaa aa aaaaaa",
    "date": "date",
    "panierUser": "3 x Jeans, 2 x T-shirts"
}

###
GET {{baseUrl}}/transactions?mid=40
Authorization: {{authToken}}

###
GET {{baseUrl}}/transactions/1?mid=40
Authorization: {{authToken}}


###
PUT {{baseUrl}}/transactions/1?mid=40
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "status": "new"
}

###
POST  {{baseUrl}}/operations?mid=40
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "type":"buy", 
    "tid":"1"
}

###
GET  {{baseUrl}}/operations?mid=40&tid=1
Authorization: {{authToken}}

###
GET  {{baseUrl}}/operations/1?mid=40
Authorization: {{authToken}}

###
PUT  {{baseUrl}}/operations/1?mid=40
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "status": "new"
}



###
GET  {{baseUrl}}/ping
Content-Type: {{contentType}}