version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections


  plateforme_api:
      image: node:alpine3.10
      ports:
        - 4000:4000
      environment:
        PORT: 4000
        MONGO_URL: "mongodb://root:password@mongo/plateformeDB"
        DATABASE_URL: "postgres://root:password@plateformeDB/plateformeDB"
        SECRET_KEY: RXCT34ZE5GFDSFD756
      volumes:
        - ./plateforme_api:/home/node/app
      working_dir: /home/node/app
      command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  api:
    image: node:alpine3.10
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      MONGO_URL: "mongodb://root:password@mongo/merchantDB"
      DATABASE_URL: "postgres://root:password@merchantDB/merchantDB"
      SECRET_KEY: RXCT34ZE5GFDSFD756
    volumes:
      - ./api:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  psp:
    image: node:alpine3.10
    ports:
      - 4004:4004
    environment:
      PORT: 4004
    volumes:
      - ./psp:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  client:
    image: node:alpine3.10
    ports:
      - 3000:3000
    environment: {}
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install; npm start"

  admin:
    image: node:alpine3.10
    ports:
      - 3002:3000
    environment: {}
    volumes:
      - ./admin:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install; npm start"

  plateformeDB:
    image: postgres:alpine
    environment:
      POSTGRES_DB: plateformeDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  merchantDB:
    image: postgres:alpine
    environment:
      POSTGRES_DB: merchantDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432


volumes:
  db-data: {}