version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine3.10
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      MONGO_URL: "mongodb://root:password@mongo/app"
      DATABASE_URL: "postgres://root:password@db/app"
      SECRET_KEY: RXCT34ZE5GFDSFD756
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"

  client:
    image: node:alpine3.10
    ports:
      - 3000:3000
    environment: {}
    volumes:
      - ./client:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install; npm start"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: {}