GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOm51bGwsImxhc3ROYW1lIjpudWxsLCJjb21wYW55TmFtZSI6ImZhY2Vib29rIiwicGhvbmUiOm51bGwsInJvbGVzIjpbInVzZXIiXSwiZW1haWwiOiJraGFsZWRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkQzF6bGpYWG1mVS9DdVFtL2p2UDY4LnhJZXlqTUJFcnc0eGlpM09keXIzMGFjRWo1U0thazYiLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTEyVDE2OjI5OjE0LjMxNVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTEyVDE2OjI5OjE0LjMxNVoiLCJhZGRyZXNzSWQiOm51bGx9LCJpYXQiOjE2MjM1MTgxNzEsImV4cCI6MTYyMzYwNDU3MX0.VD4OU-PFD0KClxcksFJNLGjQVL4H3o7RkVssCYvwtpc
###


POST http://localhost:3001/users
Content-Type: application/json

{
    "firstName": "sami",
    "lastName": "abd",
    "phone": "078689772",
    "email": "sami@gmail.com",
    "password": "user",
    "valid": true,
    "roles": ["user"],
       "address": {
        "street": "78 quai de grenelle",
        "city": "paris",
        "postalCode": 75015
    }
}
###
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "email": "khaled@gmail.com",
    "password": "user"
}


###
GET http://localhost:3001/admin/merchants
Content-Type: application/json


###

PUT http://localhost:3001/admin/merchants/valid/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJhZG1pbiIsImxhc3ROYW1lIjoiYWJkIiwiY29tcGFueU5hbWUiOm51bGwsInBob25lIjo3ODY4OTc3Miwicm9sZXMiOlsiYWRtaW4iXSwidmFsaWQiOnRydWUsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkaXVodHFaNnowcGprMjlUYmVwYXZJTzQyTVRzU3IwWGVoY2Z1YXY5YjcyMER0R2J6NVQvay4iLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTIyVDE3OjUzOjEwLjAwNFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTIyVDE3OjUzOjEwLjAwNFoiLCJhZGRyZXNzSWQiOm51bGx9LCJpYXQiOjE2MjQ0NDAzOTMsImV4cCI6MTYyNDUyNjc5M30.CIjpUuWg26eRvDeYoA_Bj7PMGhns5ipf2s-YJ5UjrBM

{
    "valid": true
}
###
POST http://localhost:3001/merchants
Content-Type: application/json

{
    "companyName": "amzone",
    "phone": "078689772",
    "email": "david@amzone.fr",
    "password": "merchant",
    "roles": ["MERCHANT"],
    "valid": false,
    "address": {
        "street": "78 quai de grenelle",
        "city": "paris",
        "postalCode": 75015
    }
}

###
GET http://localhost:3001/products
###
POST http://localhost:3001/products
Content-Type: application/json    

{
    "titre": "logo Tee Black T-Shirt",
    "price": 150,
    "image": "https://rawcdn.githack.com/jeffersonRibeiro/react-shopping-cart/ccf64841ddfdfedfce9821b2b7ff2c8075afb17c/src/static/products/12064273040195392_1.jpg"
   
}
###
GET http://localhost:3001/panier/1

###
POST http://localhost:3001/panier
Content-Type: application/json

{
    "userId": 1,
    "productId": 1
}

###
GET http://localhost:3001/transactions

###
POST http://localhost:3001/transactions
Content-Type: application/json

{
    "priceTotal": 300,
    "userId": 1,
     "panier": [
      {
        "product": {
          "id": 1,
          "titre": "logo Tee Black T-Shirt",
          "price": 150,
          "image": "https://rawcdn.githack.com/jeffersonRibeiro/react-shopping-cart/ccf64841ddfdfedfce9821b2b7ff2c8075afb17c/src/static/products/12064273040195392_1.jpg"
        },
        "product": {
            "id": 2,
            "titre": "logo Tee Black T-Shirt",
            "price": 150,
            "image": "https://rawcdn.githack.com/jeffersonRibeiro/react-shopping-cart/ccf64841ddfdfedfce9821b2b7ff2c8075afb17c/src/static/products/12064273040195392_1.jpg",
            "updatedAt": "2021-07-14T12:08:56.226Z",
            "createdAt": "2021-07-14T12:08:56.226Z"
        },
         "product": {
            "id": 3,
            "titre": "logo Tee Black T-Shirt",
            "price": 150,
            "image": "https://rawcdn.githack.com/jeffersonRibeiro/react-shopping-cart/ccf64841ddfdfedfce9821b2b7ff2c8075afb17c/src/static/products/12064273040195392_1.jpg",
            "updatedAt": "2021-07-14T12:08:56.226Z",
            "createdAt": "2021-07-14T12:08:56.226Z"
        }
      }
    ]

} 






