GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOm51bGwsImxhc3ROYW1lIjpudWxsLCJjb21wYW55TmFtZSI6ImZhY2Vib29rIiwicGhvbmUiOm51bGwsInJvbGVzIjpbInVzZXIiXSwiZW1haWwiOiJraGFsZWRAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkQzF6bGpYWG1mVS9DdVFtL2p2UDY4LnhJZXlqTUJFcnc0eGlpM09keXIzMGFjRWo1U0thazYiLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTEyVDE2OjI5OjE0LjMxNVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTEyVDE2OjI5OjE0LjMxNVoiLCJhZGRyZXNzSWQiOm51bGx9LCJpYXQiOjE2MjM1MTgxNzEsImV4cCI6MTYyMzYwNDU3MX0.VD4OU-PFD0KClxcksFJNLGjQVL4H3o7RkVssCYvwtpc
###
POST http://localhost:3001/users
Content-Type: application/json

{
    "firstName": "sami",
    "lastName": "abd",
    "phone": "078689772",
    "email": "sami@gmail.com",
    "password": "user",
    "valid": true,
    "roles": ["user"],
       "address": {
        "street": "78 quai de grenelle",
        "city": "paris",
        "postalCode": 75015
    }
}


###
GET http://localhost:3001/admin/merchants
Content-Type: application/json


###

POST http://localhost:3001/merchants
Content-Type: application/json

{
    "companyName": "google",
    "phone": "078689772",
    "email": "david@google.fr",
    "password": "merchant",
    "roles": ["MERCHANT"],
    "valid": false,
    "address": {
        "street": "78 quai de grenelle",
        "city": "paris",
        "postalCode": 75015
    }
}
###
PUT http://localhost:3001/admin/merchants/valid/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJhZG1pbiIsImxhc3ROYW1lIjoiYWJkIiwiY29tcGFueU5hbWUiOm51bGwsInBob25lIjo3ODY4OTc3Miwicm9sZXMiOlsiYWRtaW4iXSwidmFsaWQiOnRydWUsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkaXVodHFaNnowcGprMjlUYmVwYXZJTzQyTVRzU3IwWGVoY2Z1YXY5YjcyMER0R2J6NVQvay4iLCJjcmVhdGVkQXQiOiIyMDIxLTA2LTIyVDE3OjUzOjEwLjAwNFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA2LTIyVDE3OjUzOjEwLjAwNFoiLCJhZGRyZXNzSWQiOm51bGx9LCJpYXQiOjE2MjQ0NDAzOTMsImV4cCI6MTYyNDUyNjc5M30.CIjpUuWg26eRvDeYoA_Bj7PMGhns5ipf2s-YJ5UjrBM

{
    "valid": true
}
###
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "email": "khaled@gmail.com",
    "password": "user"
}




